In [3]:
import numpy as np

## create 1D Numpy Array:

temperatures_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print("Week 1 Temperatures:",temperatures_w1)


Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [4]:
## Inspection and properties:

print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7


In [5]:
##  Array operations:

fahrenheit = (temperatures_w1 * 9/5) + 32
print("Temperatures in Fahrenheit:", fahrenheit)

print("Maximum:", np.max(temperatures_w1))
print("Minimum:", np.min(temperatures_w1))
print("Mean:", np.mean(temperatures_w1))

Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum: 26.1
Minimum: 20.8
Mean: 23.542857142857144


In [6]:
##  Array slicing and indexing:

print("First 3 days:", temperatures_w1[:3])
print("Weekend (last 2 days):", temperatures_w1[-2:])
print("Middle 3 days:", temperatures_w1[2:5])

First 3 days: [22.5 25.3 20.8]
Weekend (last 2 days): [24.8 21.9]
Middle 3 days: [20.8 23.4 26.1]


In [8]:
##  Create 2D array:

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],   # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]    # Week 2
])

print("2D Temperature Array:\n", temperatures)

##  Inspect and slice the 2D array:

print("\nShape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Elements:", temperatures.size)

# Weekend temperatures for both weeks
print("Weekend Temps (Both Weeks):")
print(temperatures[:, -2:])

2D Temperature Array:
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

Shape: (2, 7)
Data Type: float64
Total Elements: 14
Weekend Temps (Both Weeks):
[[24.8 21.9]
 [22.8 20.1]]


In [10]:
## PANDAS SERIES :
import pandas as pd

## Create pandas series

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [13]:
##  Indexing and slicing

print("1st Rank Mark:", marks.iloc[0])
print("Top 3 Ranks:\n", marks.loc[['Rank1', 'Rank2', 'Rank3']])
print("3rd Rank Mark:", marks.iloc[2])

print("Marks > 90:\n", marks[marks > 90])

1st Rank Mark: 100
Top 3 Ranks:
 Rank1    100
Rank2     92
Rank3     89
dtype: int64
3rd Rank Mark: 89
Marks > 90:
 Rank1    100
Rank2     92
dtype: int64


In [18]:
## Manipulating Series:

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

marks['Rank1'] = 100
marks = marks.drop('Rank5')

cgpa = marks / 10
print("Updated Marks:\n", marks)
print("CGPA:\n", cgpa)

Updated Marks:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [19]:
## PANDAS DATAFRAME :

##   Creating Dataframe:
transactions = pd.DataFrame({
    'TransactionID': [101,102,103,104,105,106,107,108,109,110],
    'ProductCategory': ['Electronics','Clothing','Electronics','Furniture',
                        'Clothing','Electronics','Furniture','Clothing',
                        'Furniture','Electronics'],
    'Region': ['North','South','North','East','West',
               'North','East','West','South','North'],
    'Amount': [200,150,300,450,200,250,300,180,350,400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [20]:
## Data Exploration :

print(transactions.head())
print(transactions.tail())
print("Shape:", transactions.shape)
print("Columns:", transactions.columns)
print(transactions.dtypes)

print(transactions[['ProductCategory', 'Amount']])
print(transactions.iloc[:, -3:])

print(transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)])

print(transactions['ProductCategory'].value_counts())
print(transactions['Region'].unique())

print(transactions.groupby('Region')['Amount'].mean())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
Shape: (10, 4)
Columns: Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object
  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture   

In [21]:
##Manipulating the Dataframe :

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

transactions['Discount'] = transactions['Amount'] * 0.10

transactions = transactions[transactions['TransactionID'] != 109]

transactions.drop(columns=['Discount'], inplace=True)

print("Final DataFrame:\n", transactions)

Final DataFrame:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
